# Importing the required libraries
import openai
import tkinter as tk

# Setting up the API key for OpenAI
openai.api_key = "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"

# Function to generate a response using GPT-3 given a prompt
def generate_response():
    prompt = entry.get()    # Get the user's prompt from the input field
    response = openai.Completion.create(
        engine="davinci",
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.5,
    )
    message = response.choices[0].text.strip()
    text.delete("1.0", tk.END)    # Clear the output text field
    text.insert(tk.END, message)    # Display the response in the output text field

# Create a new GUI window
root = tk.Tk()

# Create a label asking the user to enter their prompt
label = tk.Label(root, text="Enter your prompt:")
label.pack()

# Create an input field for the user to enter their prompt
entry = tk.Entry(root)
entry.pack()

# Create a button to submit the user's prompt and display the response
button = tk.Button(root, text="Ask", command=generate_response)
button.pack()

# Create a text field to display the response generated by GPT-3
text = tk.Text(root)
text.pack()

# Run the GUI window
root.mainloop()